name: Build

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build API
        run: cd packages/api && yarn build
      - name: Create package tgz
        run: cd packages/api && yarn pack && mv package.tgz actual-api.tgz
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: actual-api
          path: packages/api/actual-api.tgz

  crdt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build CRDT
        run: cd packages/crdt && yarn build
      - name: Create package tgz
        run: cd packages/crdt && yarn pack && mv package.tgz actual-crdt.tgz
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: actual-crdt
          path: packages/crdt/actual-crdt.tgz

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Web
        run: ./bin/package-browser
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: actual-web
          path: packages/desktop-client/build

  electron:
    # As electron builds take longer, we only run them in master.
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Electron
        run: ./bin/package-electron
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: actual-electron-${{ matrix.os }}
          path: |
            packages/desktop-electron/dist/*.dmg
            packages/desktop-electron/dist/*.AppImage
  electron-windows:
    # As electron builds take longer, we only run them in master.
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Electron
        env:
          CSC_LINK: ${{ secrets.WIN_CERT_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.WIN_CERT_PASS }}
        run: ./bin/package-electron
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: actual-electron-windows-latest
          path: packages/desktop-electron/dist/*.exe
